private_key_path: "/root/.ssh/id_rsa"

# Common Borg backup settings
cron: 0 3 * * *
cron_filename: backup-files.sh
repository_path: "ssh://u494207-sub1@u494207-sub1.your-storagebox.de"
repository_port: 23
repository_name: "my-backups"
repository_passphrase: "secret"
borg_prune_params:
  - --keep-within=10d
  - --keep-weekly=7
  - --keep-monthly=10

# Files backup specific
include_folders:
  - ./
  - ./src

exclude_folders:
  - ./tmp
  - ./logs
  - ./venv

# DB backup specific
db_host: 127.0.0.1
db_user:
db_password:
db_name:
db_backup_local_dir: /tmp/
